name: neck_check
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1

  # Bloc 관련
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  meta: ^1.16.0

  http: ^1.6.0     
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
